@echo off
title ingame_start
nircmd win setsize title ingame_start 3020 1520 800 600
mode con: cols=60 lines=15
nircmd win settopmost title ingame_start 1
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
python ingame.py
pause