@echo off
title start
nircmd win setsize title start 3020 1520 800 600
mode con: cols=60 lines=15
nircmd win settopmost title start 1
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
python main.py
pause